apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
    service.beta.openshift.io/inject-cabundle: "true"
  name: platform-operators-rukpak-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: platform-operators-rukpak-webhook-service
      namespace: openshift-platform-operators
      path: /validate-core-rukpak-io-v1alpha1-bundle
  failurePolicy: Fail
  name: vbundles.core.rukpak.io
  rules:
  - apiGroups:
    - core.rukpak.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bundles
  sideEffects: None
