apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
    service.beta.openshift.io/inject-cabundle: "true"
  name: platform-operators-rukpak-webhook-tls
  namespace: openshift-platform-operators
