apiVersion: v1
kind: Service
metadata:
  annotations:
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
    service.beta.openshift.io/serving-cert-secret-name: platform-operators-rukpak-webhook-tls
  name: platform-operators-rukpak-webhook-service
  namespace: openshift-platform-operators
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: webhooks
